version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bvc-flash-sls-poc"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ezjvp6wif021"
s3_prefix = "bvc-flash-sls-poc"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
